// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_C6wQeOlcxS2TslmpMZji_2p8gj811g',
    appId: '1:892932890509:web:a6c139e092fb230d7b27c4',
    messagingSenderId: '892932890509',
    projectId: 'service-app-9fc1e',
    authDomain: 'service-app-9fc1e.firebaseapp.com',
    storageBucket: 'service-app-9fc1e.firebasestorage.app',
    measurementId: 'G-EHTXC7ZTZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRCn8eAet7_UWdwNO2J0Jji1G4kRVby0',
    appId: '1:892932890509:android:659ee37144459ba47b27c4',
    messagingSenderId: '892932890509',
    projectId: 'service-app-9fc1e',
    storageBucket: 'service-app-9fc1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwlrldz-hFaKD8of4d6LDGoEnRMPOrhqc',
    appId: '1:892932890509:ios:de14a964a6c9080d7b27c4',
    messagingSenderId: '892932890509',
    projectId: 'service-app-9fc1e',
    storageBucket: 'service-app-9fc1e.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwlrldz-hFaKD8of4d6LDGoEnRMPOrhqc',
    appId: '1:892932890509:ios:de14a964a6c9080d7b27c4',
    messagingSenderId: '892932890509',
    projectId: 'service-app-9fc1e',
    storageBucket: 'service-app-9fc1e.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6_C6wQeOlcxS2TslmpMZji_2p8gj811g',
    appId: '1:892932890509:web:ff3d0db8f65530777b27c4',
    messagingSenderId: '892932890509',
    projectId: 'service-app-9fc1e',
    authDomain: 'service-app-9fc1e.firebaseapp.com',
    storageBucket: 'service-app-9fc1e.firebasestorage.app',
    measurementId: 'G-VTDMKZYFZD',
  );
}
